#!/bin/bash

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

if command_exists node; then
	# Ok, pass..
	:
else
  # Check if nvm is installed
  if [ -s "$NVM_DIR/nvm.sh" ] || [ -s "$HOME/.nvm/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  . "$HOME/.nvm/nvm.sh"
    # node.js is not installed, but nvm yes
    nvm install 24
  else
    # node.js is not installed, neither nvm
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    echo "Please close the console and launch again this script!"
    exit 0
  fi
fi

node_version=$(node --version)

if ! [[ "$node_version" == v24.* ]]; then
    echo "Warning! You are not using node.js version 24, this application is not guaranteed to work."
fi

npm install -g cross-env
npm install -g tsx

npm run setup
npm run build
npm link
