#!/bin/bash

if which node > /dev/null; then
	# Ok, pass..
	:
else
    echo "NODEJS NOT is installed, installing NVM and NODEJS 18"

    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

    exec bash

    nvm install 18
    nvm use 18
fi

node_version=$(node --version)

if ! [[ "$node_version" == v18.* ]]; then
    echo "Warning! You are not using node.js version 18, this application is not guaranteed to work."
fi

npm install -g cross-env
npm install -g tsx

npm run build
npm link