#!/bin/bash

marzian_dir="$(dirname "$(realpath "$0")")"
working_dir="$(pwd)"

# portArg=""

# if [ $# -ge 2 ]; then
#   portArg="$1 $2"
# fi

cd $marzian_dir && cross-env WORKING_DIR=$working_dir npm run start
