#!/bin/bash

project="$(dirname "$(realpath "$0")")"

portArg=""

if [ $# -ge 2 ]; then
  portArg="$1 $2"
fi

npx --yes cross-env NODE_ENV=production "$project/src/server.ts" --path "$project" $portArg
